services:
  - type: web
    name: disaster-response-api
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./disaster-response-ai/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
