# Base python image
FROM python:3.11-slim

WORKDIR /app

COPY ./disaster-response-ai/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./disaster-response-ai /app

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
